### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by Appolonius001** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#1]
how does this work? i cant tell what things are connected to.
does this save the prompt as a text file next to the image? or renames the image as the prompt?

**Comment by MNeMoNiCuZ** [comment]
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/60541708/2c411771-ed7d-4528-8610-96d4d53c2ae0)
If you create a new node, it should come un-connected and it should be a little clearer.

What the Save Text File_mne-does is that it saves a .txt-file in your output folder. You get to input what text the file contains with the "text" input pin.

This can be useful if you want to create an automatic caption file based on your input prompt, which could be useful for training models with your generated images. Especially if your prompt contains random elements such as wildcards, and you want the resulting text output actually used.

The rest of the settings are just determining where the file is saved, and how it is named.

Path = Where you want to save the file. Note that this starts from the extensions folder or something, so you may need to format it like this `./output/[time(%Y-%m-%d)]/`
filename_prefix = This is what you want your file name to save as before the number
filename_delimiter = This is what you want to be between the file name and the number
filename_number_padding = This is how many 0's to put before numbers so that the number length is always the same. A padding of 3 means it will write 001, 002, instead of 1 and 2.
overwrite_mode = I think this is an option for if it should overwrite if it finds an existing file with the same name.

**Comment by Appolonius001** [comment]
unless im missing something simple, which i could be, the node is not putting out a text file. also thank you for the fast reply :D
![Untitled](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/111724828/106b7f4e-9763-4f2d-9777-7670878ef5b6)

**Comment by Appolonius001** [comment]
ok so i got it to work by using
`ComfyUI\output/[time(%Y-%m-%d)]`
strange, might it have anything to do with having the portable version of comfyui installed?

**Comment by MNeMoNiCuZ** [comment]
Oh, very possible! I've had another issue where something that worked on portable didn't work on git clone.
I have no idea how this works technically, hell this node is someone elses, I just added the STRING output as I needed the modified output so I could name the output image file exactly the same.

Happy it's resolved!

**Comment by Appolonius001** [comment]
ah nice, ive had an issue with auto naming my images because i use wildcards, but i also use weights.. and filesnames dont like some symbols.

ex prompt: `__random__, __random__, __random__` reads a wildcard like this

```
(__adverb__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__adjective__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__noun__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__object__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__subject__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__verb__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(by __artist__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(in __biome__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__style__ style:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
(__mod__:{0.1|0.2|0.3|0.4|0.5|0.6|0.7|0.8|0.9|1.0|1.1|1.2|1.3|1.4|1.5})
```
yea.. lol and each one of those randomly picks from multiple wildcards in the above.

how it works:  `__random__ -> picks (__adverb__:1.3) -> picks sci-fi_adverb.txt = Final Prompt: (Robotically:1.3)`

**so saving the final prompt will not save it as a filename because of the ('s and )'s**

(i like randomness lol)

**Comment by MNeMoNiCuZ** [comment]
I would suggest you create another wildcard file for your weights. I have a file called "01-15.txt" which has those weights in it for example, and when I want random between 01 and 1.5, I just call on that file with `__01-15__`

Filenames don't support colons (:), but you can replace that with another character.
So you can't save the full prompt as a filename, but you should be able to fully save the prompt in the .txt file if you put in your positive prompt as the text-input for the save node.

Are you having problems with this?

**Comment by Appolonius001** [comment]
it does save inside a .txt file just fine.
do mean manually changing the filename? or i wonder if there is a way to code that in?
like 'find :, replace with - ' i am not great with coding so i have 0 clue :/

**Comment by MNeMoNiCuZ** [comment]
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/60541708/34f3e079-d383-4d52-90e3-1e0fa1e24c1a)
If you look to the right of the "Save Text File_mne"-node, you have the "Anything Everywhere?"-node, which transfers the output string into a variable called "filename". See screenshot above.


This is the filename that we forward to the Save Image-node. See the below. It's forwarded to the "filename" input there.
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/60541708/81cf72ab-f48e-4d9b-9e81-0374380885ec)


This means that we want to modify the string before we send it into the "Anything Everywhere?"-node.
Try using the "Text Find and Replace"-node from the 'WAS Node Suite', like this:
![image](https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes/assets/60541708/67cb9a1e-912f-4844-8e02-5ea8d0673577)


This way you replace all: with -, as you suggested above. This should be savable.

**Comment by Appolonius001** [comment]
wow! that's amazing. thank you! you rock :D
testing now
