### ISSUE TITLE
Is this GROQ image generation? 

### ISSUE THREAD

**Issue by filmgab** [MNeMoNiCuZ/ComfyUI-mnemic-nodes#4]
I read the civitai tutorial and I’m confused on what using the GROQ api actually does. Does using the API generate the image remotely  using Groq's Lang Processing Units GROQ’s (LPUs) or if it only generates prompts, and you still need to use a checkpoint locally with your own GPU.

**Comment by MNeMoNiCuZ** [comment]
You have understood correctly with your second option.
It's not image generation, just prompt generation.

Or any query you would like to send it. It wouldn't have to be specifically for a prompt. It's just a text LLM API query.

Send it an input, receive its output. Now you can do it in Comfy for all sorts of uses.

Comfy is not limited to image generation mind you. It can be used for other automation tasks too. Just create a workflow and let it run continously :)

**Comment by MNeMoNiCuZ** [comment]
Right, yeah you can use it for whatever you have nodes for.

The benefit is that you can use existing nodes and combine stuff easily if you create workflows with it, + host them online, run them remotely and such I guess, I haven't done that though.

The downside is that instead of coding simple functionality in Python, you now have to make that into nodes.

Regarding the dying of JARVIS, there's not much to do if you need the soulstone back, it is what it is :)


I don't consider myself a coder either, but here I am uploading stuff to Github. GPT4 can make anyone produce code-like things as long as they are simple enough!


So you want to create a virtual assistant? It doesn't sound like something that Comfy would be ideal for. It may be a fun experiment, but it's just going to give you more problem than benefits as it makes everything more convoluted.

I would consider using something like Autogen as a basis for it. There are simple guides on youtube. Look them up, run the language models locally using LM Studio, and set up a group of "abilities" for your main leading/task-management (JARVIS) agent.

I'm sure there may be Github repositories for this as well.

Good luck!
